[workspace]
authors = ["Oliver Borchert <oliver.borchert@quantco.com>"]
channels = ["conda-forge"]
name = "polars"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.0,<3"
maturin = ">=1.8.7,<2"
pytest = ">=8.4.1,<9"
jupyter = ">=1.1.1,<2"
pip = ">=25.1.1,<26"
hypothesis = ">=6.135.13,<7"
pytest-xdist = ">=3.7.0,<4"
pytest-benchmark = ">=5.1.0,<6"
pandas = ">=2.3.0,<3"
pyarrow = ">=20.0.0,<21"
