[project]
authors = ["Oliver Borchert <oliver.borchert@quantco.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "polars"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
hypothesis = ">=6.125.1,<7"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
maturin = ">=1.8.2,<2"
numpy = ">=2.2.2,<3"
pip = ">=25.0,<26"
pytest = ">=8.3.4,<9"
python = ">=3.13.1,<3.14"
pyarrow = ">=19.0.1,<20"
duckdb-engine = ">=0.15.0,<0.16"
duckdb = ">=1.2.1,<2"
python-duckdb = ">=1.2.1,<2"
ruff = "==0.9.4"
